name: Run Energy Simulation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

permissions: read-all

jobs:
  update-version:
    if: >
      github.event.review.state == 'approved' && 
          github.event.pull_request.state == 'open'
    runs-on: windows-latest
    permissions:
      contents: write
  simulate:
    runs-on: ubuntu-latest  # Or another OS like windows-latest or macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Script
        run: |
          python creator.py

      - name: Push Repo
        run: |
          git config --global user.email "antialberteinstein@gmail.com"
          git config --global user.name "Github Actions"
          git add .
          git commit -m "Update energy consumption"
          git push -u origin
